"""Add week column to WeeklyMealPlan

Revision ID: 3956740f8671
Revises: 7231aa7c7488
Create Date: 2023-08-28 22:33:42.732637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3956740f8671'
down_revision = '7231aa7c7488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week', sa.String(length=50), nullable=True))
        batch_op.drop_column('week_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_number', sa.INTEGER(), nullable=False))
        batch_op.drop_column('week')

    # ### end Alembic commands ###
