"""delete col

Revision ID: 7231aa7c7488
Revises: 
Create Date: 2023-08-28 21:31:39.845059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7231aa7c7488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_meal_plan', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_meal_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
